name: Build and release

on: [push]

env:
  GITHUB_TOKEN: ${{secrets.GHR_TOKEN}}

jobs:
  vulnerabilitycheck:
    name: Vulnerabilities scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.1'
          check-latest: true

      - name: Get scanner tool
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Scan for vulnerabilities
        run: govulncheck ./...

  test:
    name: Tests
    runs-on: ubuntu-latest
    container: golang:latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...




